=== SaschM/Yoko-Tawada-XML/AssessmentXML.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT collection (book,text)>
<!-- to be used if the separate xml files were compiled into one file -->
<!-- collection in the root element -->
<!ELEMENT book (bookTitle+,datePublished+,publisher+,writers+)>
<!ELEMENT bookTitle (#PCDATA)>
<!ATTLIST bookTitle bookLanguage CDATA #REQUIRED>
<!ELEMENT datePublished (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ATTLIST publisher country CDATA #REQUIRED>
<!ELEMENT writers (author,translator*)>
<!ELEMENT author (#PCDATA)>
<!ATTLIST author language CDATA #REQUIRED>
<!ELEMENT translator (#PCDATA)>
<!ATTLIST translator languageFrom CDATA #REQUIRED>
<!ATTLIST translator languageTo CDATA #REQUIRED>
<!ELEMENT text (textTitle,originalTitle*,textEquivalent*,pages,character+,theme+,body)>
<!ATTLIST text textLanguage CDATA #REQUIRED>
<!ELEMENT textTitle (#PCDATA)>
<!ELEMENT originalTitle (#PCDATA)>
<!ATTLIST originalTitle language CDATA #REQUIRED>
<!ATTLIST originalTitle fromBook CDATA #REQUIRED>
<!ELEMENT textEquivalent (#PCDATA)>
<!ATTLIST textEquivalent equivWriter CDATA #REQUIRED>
<!ATTLIST textEquivalent equivLanguage CDATA #REQUIRED>
<!ATTLIST textEquivalent fromBook CDATA #REQUIRED>
<!ELEMENT pages (#PCDATA)>
<!ELEMENT character (#PCDATA)>
<!ATTLIST character characterType CDATA #REQUIRED>
<!ATTLIST character characterEquiv CDATA #IMPLIED >
<!ELEMENT theme (#PCDATA) >
<!ELEMENT body (page+)>
<!ELEMENT page (chapter*,p+) >
<!ATTLIST page pageNo CDATA #REQUIRED>
<!ELEMENT chapter EMPTY>
<!ATTLIST chapter chapterNo CDATA #REQUIRED>
<!ATTLIST chapter chapterTitle CDATA #IMPLIED>
<!ELEMENT p (line+)>
<!ATTLIST p pNo CDATA #REQUIRED>
<!ELEMENT line (#PCDATA|firstletter|name|speech|italics|animal)*>
<!ELEMENT firstletter (#PCDATA)>
<!ATTLIST line lineNo CDATA #REQUIRED>
<!ELEMENT name (#PCDATA|animal)* >
<!ELEMENT speech (#PCDATA|italics|animal)* >
<!ATTLIST speech speaker CDATA #REQUIRED >
<!ATTLIST speech type CDATA #REQUIRED >
<!ELEMENT italics (#PCDATA) >
<!ELEMENT animal (#PCDATA)>
<!ATTLIST animal animalType CDATA #REQUIRED>
<!ENTITY semi-colon "&#59;">
<!ENTITY colon "&#58;">
<!ENTITY umlaut-u-lowercase "&#252;" >
<!ENTITY umlaut-u-uppercase "&#220;" >
<!ENTITY umlaut-a-lowercase "&#228;" >
<!ENTITY eszett "&#223;" >
<!ENTITY umlaut-o-lowercase "&#246;" >
<!ENTITY umlaut-o-capital "&#214;" >
<!ENTITY acute-e-lowercase "&#233;" >

=== SaschM/Yoko-Tawada-XML/Talisman.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE collection SYSTEM "file:/Users/saschamorgan-evans/Desktop/Digital%20Humanities%20MA:MSc/AssessmentXML.dtd">
<!-- Talisman German Version-->
<collection>
    <book>
        <bookTitle bookLanguage="German">Talisman</bookTitle>
        <datePublished>2015</datePublished>
        <publisher country="Germany">Impressum</publisher>
        <writers>
            <author language="German">Yoko Tawada</author>
        </writers>
    </book>
    <text textLanguage="German">
        <textTitle>Talisman</textTitle>
        <textEquivalent equivWriter="Yoko Tawada and Susan Bernofsky" equivLanguage="English" fromBook="Where Europe Begins">The Talisman</textEquivalent>
        <pages>53-59</pages>
        <character characterType="main and narrator">Narrator</character>
        <character characterType="secondary">Gilda</character>
        <theme>The Foreign</theme>
        <theme>Foreign Gaze</theme>
        <theme>Defamiliarisation</theme>
        <body>
            <page pageNo="53">
                <p pNo="1">
                    <line lineNo="1"><firstletter>E</firstletter>s gibt in dieser Stadt viele Frauen, die ein St&#252;ck</line>
                    <line lineNo="2">Metall am Ohr tragen. Sie lassen sich daf&#252;ur ex-</line>
                    <line lineNo="3">tra ein Loch ins Ohrl&#228;ppchen machen. Ich wollte</line>
                    <line lineNo="4">schon kurz nach meiner Ankunft fragen, was das</line>
                    <line lineNo="5">Metallst&#252;ck am Ohr bedeutet. Ich war blo&#223; nicht</line>
                    <line lineNo="6">sicher, ob ich dar&#252;ber offen sprechen darf. In mei-</line>
                    <line lineNo="7">nem Reiserf&#252;hrer steht zum Beispiel, dass man in</line>
                    <line lineNo="8">Europa einer noch nicht vertrauten Person keine</line>
                    <line lineNo="9">Frage stellen solle, die direkt ihren K&#246;rper oder ihre</line>
                    <line lineNo="10">Religion betrifft. Manchmal dachte ich mir, dass das</line>
                    <line lineNo="11">Metallst&#252;ck-besonders wenn ich eines in der Form</line>
                    <line lineNo="12">einer Sicher, eines Bogens oder eines Ankers sah</line>
                    <line lineNo="13">-eine Art Talisman sein k&#246;nnte.</line>
                </p>
                <p pNo="2">
                    <line lineNo="14">Die Stadt scheint mir auf den ersten Blick nicht</line>
                    <line lineNo="15">so gef&#228;hrlich zu sein. Warum tragen dann aber</line>
                    <line lineNo="16">so viele Frauen einen Talisman auf den Stra&#223;en?</line>
                    <line lineNo="17">Allerdings ist es manchmal unheimlich, alleine in</line>
                    <line lineNo="18">der Stadt unterwegs zu sein. Es gibt einfach zu we-</line>
                    <line lineNo="19">nig Menschen, die in dieser Stadt wohnen. Sogar</line>
                    <line lineNo="20">tags&#252;ber kam es schol h&#228;ufig vor, dass ich auf dem</line>
                    <line lineNo="21">Weg vom Bahnhof bis nach Hause keinen einzigen</line>
                    <line lineNo="22">Menschen sah.</line>
                </p>
                <p pNo="3">
                    <line lineNo="23">Wenn das Metallst&#252;ck am Ohr eine Art Talisman</line>
                    <line lineNo="24">sein sollte, warum ist es unter Frauen so verbreitet?</line>
                    <line lineNo="25">Ich kannte den Namen der b&#246;sen Kraft nicht, vor</line>
                    <line lineNo="26">der sich die Frauen mit Hilfe des Talismans sch&#252;tzen</line>
                </p>
            </page>
            <page pageNo="54">
                <p pNo="3">
                    <line lineNo="27">wollten. Sie verrieten mir den Namen nicht und ich</line>
                    <line lineNo="28">habe noch nie richtig versucht, ihn herauszufin-</line>
                    <line lineNo="29">den. <speech speaker="people/they" type="indirect">Bei uns sagt man auch, dass der Name eines</speech></line>
                    <line lineNo="30"><speech speaker="people/they" type="indirect">gef&#228;hrlichen Wesens nicht laut ausgesprochen</speech></line>
                    <line lineNo="31"><speech speaker="people/they" type="indirect">werden solle. Sonst erscheine dieses Wesen in der</speech></line>
                    <line lineNo="32"><speech speaker="people/they" type="indirect">Wirklichkeit. Man m&#252;sse es indirekt nennen</speech></line>
                    <line lineNo="33"><speech speaker="people/they" type="indirect">Beispiel kann man an der Stelle seines Names</speech></line>
                    <line lineNo="34"><speech speaker="people/they" type="indirect">einfach &gt;&gt;es&lt;&lt;sagen.</speech></line>
                </p>
                <p pNo="4">
                    <line lineNo="35"><name>Gilda</name>eine Studentin, die in demselben Haus</line>
                    <line lineNo="36">wohnte wie ich, trug immer ein dreieckiges Metall-</line>
                    <line lineNo="37">st&#252;ck am Ohr. Sie erz&#228;lte mir - als wir uns zum</line>
                    <line lineNo="38">ersten Mal l&#228;nger unterhielten-, dass <speech speaker="Gilda" type="indirect">eine f&#252;nf-</speech></line>
                    <line lineNo="39"><speech speaker="Gilda" type="indirect">undf&#252;nfzigj&#228;hrige Bibliothekarin in der Universit&#228;t</speech></line>
                    <line lineNo="40"><speech speaker="Gilda" type="indirect">einen Tag zuvor Selbstmord begangen habe.</speech>Diese</line>
                    <line lineNo="41">Bibliothekarin wehtre sich bis zum Tode gegen die</line>
                    <line lineNo="42">Einf&#252;hrung des Computers in ihrer Abteilung. <name>Gilda</name></line>
                    <line lineNo="43">sagte, <speech speaker="Gilda" type="indirect">doe Frau sei nicht intelligent gewesen, denn</speech></line>
                    <line lineNo="44"><speech speaker="Gilda" type="indirect">sie h&#228;tte nie verstanden, dass ein Computer nur ein</speech></line>
                    <line lineNo="45"><speech speaker="Gilda" type="indirect">Werkzeug und kein Monster sei. Die Einf&#252;hrung des</speech></line>
                    <line lineNo="46"><speech speaker="Gilda" type="indirect">Computers sei aber angeblich nicht der Grund ih-</speech></line>
                    <line lineNo="47"><speech speaker="Gilda" type="indirect">res Selbstmords gewesen. Sie habe schon seit zehn</speech></line>
                    <line lineNo="48"><speech speaker="Gilda" type="indirect">Jahren eine starke Depression gehabt. Si lebte</speech></line>
                    <line lineNo="49"><speech speaker="Gilda" type="indirect">allein</speech>sagte Gilda und ber&#252;hrte dabei mit dem</line>
                    <line lineNo="50">Zeigefinger ihr dreieckiges Metallst&#252;ck.</line>
                </p>
                <p pNo="5">
                    <line lineNo="51"><speech speaker="narrator" type="indirect">Was f&#252;r eine Bedeutung hat das Metallst&#252;ck</speech></line>
                    <line lineNo="52">fragte ich <name>Gilda</name>. Sie blickte mich verwundert an</line>
                    <line lineNo="53">fragte nach, <speech speaker="Gilda" type="indirect">ob ich ihren &gt;&gt;Ohrring&lt;&lt;meine.</speech>Das</line>
                    <line lineNo="54">Wort &gt;&gt;Ring&lt;&lt; wirkte auf mich etwas beunruhigend.</line>
                    <line lineNo="55">Gilda sagte desinteressiert, <speech speaker="Gilda" type="indirect">der Ohrring sei nur ein</speech></line>
                    <line lineNo="56"><speech speaker="Gilda" type="indirect">Schmuckst&#252;ck, er habe keine Bedeutung</speech></line>
                </p>
            </page>
            <page pageNo="55">
                <p pNo="6">
                    <line lineNo="57">Wie ich es schon vermuter hatte, wollte <name>Gilda</name></line>
                    <line lineNo="58">nicht &#252;ber die Bedeutung des Ohrrings reden. Statt-</line>
                    <line lineNo="59">dessen erz&#228;hlte sie mir, <speech speaker="Gilda" type="indirect">dass Frauen, die ein hohes</speech></line>
                    <line lineNo="60"><speech speaker="Gilda" type="indirect">Bildungsniveau haben, sich relativ sp&#228;t ein Loch ins</speech></line>
                    <line lineNo="61"><speech speaker="Gilda" type="indirect">Ohr machen lassen, w&#228;hrend Frauen aus der Ar-</speech></line>
                    <line lineNo="62"><speech speaker="Gilda" type="indirect">beiterschicht schon als M&#228;dchen Ohrringe tragen</speech></line>
                </p>
                <p pNo="7">
                    <line lineNo="63">Ich hatte in einem Buch gelesen, dass es Kulturen</line>
                    <line lineNo="64">gebe, in deinen ein Tel des Geschlechtsorgens bei</line>
                    <line lineNo="65">der Initiations-Zeremonie abgeschnitten wird. Das</line>
                    <line lineNo="66">Geschlechtsorgan k&#246;nne dabei aber urch einen</line>
                    <line lineNo="67">anderen K&#246;rperteil vertreten werden&#59; zum Beispiel</line>
                    <line lineNo="68">durch die F&#252;&#223;e&#59; oder durch die Ohren. Nicht der</line>
                    <line lineNo="69">Ohrring, sondern das Lochen des Ohrl&#228;ppchens</line>
                    <line lineNo="70">m&#252;sste in diesem Fall die Bedeutung tragen.</line>
                </p>
                <p pNo="8">
                    <line lineNo="71">Warum war <name>Gilda</name> aber so &#228;ngstlich? Eines Tages</line>
                    <line lineNo="72">stellte sie zwei <animal animalType="dog/canine">Hunde</animal> aus Porzellan aud die Fenster-</line>
                    <line lineNo="73">bank. Die Blument&#246;pfe, die ich ihr geschenkt hatte,</line>
